# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ActivityTypeEnum(object):

    """Implementation of the 'ActivityTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        CREATED: TODO: type description here.
        UPDATED: TODO: type description here.
        DELETED: TODO: type description here.

    """

    CREATED = 'CREATED'

    UPDATED = 'UPDATED'

    DELETED = 'DELETED'
