# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AllocationByCode(object):

    """Implementation of the 'AllocationByCode' model.

    TODO: type model description here.

    Attributes:
        code (string): TODO: type description here.
        name (string): TODO: type description here.
        balance (float): TODO: type description here.
        weight (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": 'code',
        "name": 'name',
        "balance": 'balance',
        "weight": 'weight'
    }

    def __init__(self,
                 code=None,
                 name=None,
                 balance=None,
                 weight=None):
        """Constructor for the AllocationByCode class"""

        # Initialize members of the class
        self.code = code
        self.name = name
        self.balance = balance
        self.weight = weight

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        code = dictionary.get('code')
        name = dictionary.get('name')
        balance = dictionary.get('balance')
        weight = dictionary.get('weight')

        # Return an object of this model
        return cls(code,
                   name,
                   balance,
                   weight)
