# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser


class AllocationList(object):

    """Implementation of the 'AllocationList' model.

    TODO: type model description here.

    Attributes:
        valuation_date (date): TODO: type description here.
        balance (float): TODO: type description here.
        invested (float): TODO: type description here.
        earnings (float): TODO: type description here.
        cash_active (float): TODO: type description here.
        trade_total (float): TODO: type description here.
        performance (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "valuation_date": 'valuation_date',
        "balance": 'balance',
        "invested": 'invested',
        "earnings": 'earnings',
        "cash_active": 'cash_active',
        "trade_total": 'trade_total',
        "performance": 'performance'
    }

    def __init__(self,
                 valuation_date=None,
                 balance=None,
                 invested=None,
                 earnings=None,
                 cash_active=None,
                 trade_total=None,
                 performance=None):
        """Constructor for the AllocationList class"""

        # Initialize members of the class
        self.valuation_date = valuation_date
        self.balance = balance
        self.invested = invested
        self.earnings = earnings
        self.cash_active = cash_active
        self.trade_total = trade_total
        self.performance = performance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        valuation_date = dateutil.parser.parse(dictionary.get('valuation_date')).date() if dictionary.get('valuation_date') else None
        balance = dictionary.get('balance')
        invested = dictionary.get('invested')
        earnings = dictionary.get('earnings')
        cash_active = dictionary.get('cash_active')
        trade_total = dictionary.get('trade_total')
        performance = dictionary.get('performance')

        # Return an object of this model
        return cls(valuation_date,
                   balance,
                   invested,
                   earnings,
                   cash_active,
                   trade_total,
                   performance)
