# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser

from nucoroapiv2.api_helper import APIHelper
from nucoroapiv2.models.country_field import CountryField


class ApplicationClientUpdate(object):

    """Implementation of the 'ApplicationClientUpdate' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        email (string): TODO: type description here.
        birthdate (date): TODO: type description here.
        tos_consent (bool): TODO: type description here.
        marketing_consent (bool): TODO: type description here.
        data_consent (bool): TODO: type description here.
        tos_consent_date (date): TODO: type description here.
        tax_information (list of string): TODO: type description here.
        country_birth (CountryField): TODO: type description here.
        last_login (datetime): TODO: type description here.
        referred_by (string): TODO: type description here.
        successful_referrals (int): TODO: type description here.
        kyc_verified (bool): TODO: type description here.
        is_verified (bool): TODO: type description here.
        fee_segments (list of string): TODO: type description here.
        extra_data (dict): TODO: type description here.
        portfolios (list of string): TODO: type description here.
        onboarded_by (string): TODO: type description here.
        risk_level (int): TODO: type description here.
        onboarding_token (string): TODO: type description here.
        password (string): TODO: type description here.
        email_verified_last_request (datetime): TODO: type description here.
        uuid (uuid|string): TODO: type description here.
        created (datetime): TODO: type description here.
        updated (datetime): TODO: type description here.
        comments (string): TODO: type description here.
        status (StatusB65Enum): TODO: type description here.
        email_verified (bool): TODO: type description here.
        email_verify_last_request (datetime): TODO: type description here.
        title (TitleEnum): TODO: type description here.
        first_name (string): TODO: type description here.
        middle_name (string): TODO: type description here.
        last_name (string): TODO: type description here.
        gender (GenderEnum): TODO: type description here.
        marital_status (MaritalStatusEnum): TODO: type description here.
        phone_number (string): TODO: type description here.
        phone_number_verified (datetime): TODO: type description here.
        language (string): TODO: type description here.
        employment_status (EmploymentStatusEnum): TODO: type description
            here.
        profession (string): TODO: type description here.
        referral_code (string): TODO: type description here.
        activated (datetime): TODO: type description here.
        utm_source (string): TODO: type description here.
        utm_medium (string): TODO: type description here.
        utm_campaign (string): TODO: type description here.
        utm_term (string): TODO: type description here.
        utm_content (string): TODO: type description here.
        marketing_consent_date (date): TODO: type description here.
        data_consent_date (date): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "email": 'email',
        "tos_consent_date": 'tos_consent_date',
        "tax_information": 'tax_information',
        "country_birth": 'country_birth',
        "last_login": 'last_login',
        "successful_referrals": 'successful_referrals',
        "kyc_verified": 'kyc_verified',
        "is_verified": 'is_verified',
        "fee_segments": 'fee_segments',
        "portfolios": 'portfolios',
        "risk_level": 'risk_level',
        "onboarding_token": 'onboarding_token',
        "uuid": 'uuid',
        "created": 'created',
        "updated": 'updated',
        "status": 'status',
        "language": 'language',
        "marketing_consent_date": 'marketing_consent_date',
        "data_consent_date": 'data_consent_date',
        "birthdate": 'birthdate',
        "tos_consent": 'tos_consent',
        "marketing_consent": 'marketing_consent',
        "data_consent": 'data_consent',
        "referred_by": 'referred_by',
        "extra_data": 'extra_data',
        "onboarded_by": 'onboarded_by',
        "password": 'password',
        "email_verified_last_request": 'email_verified_last_request',
        "comments": 'comments',
        "email_verified": 'email_verified',
        "email_verify_last_request": 'email_verify_last_request',
        "title": 'title',
        "first_name": 'first_name',
        "middle_name": 'middle_name',
        "last_name": 'last_name',
        "gender": 'gender',
        "marital_status": 'marital_status',
        "phone_number": 'phone_number',
        "phone_number_verified": 'phone_number_verified',
        "employment_status": 'employment_status',
        "profession": 'profession',
        "referral_code": 'referral_code',
        "activated": 'activated',
        "utm_source": 'utm_source',
        "utm_medium": 'utm_medium',
        "utm_campaign": 'utm_campaign',
        "utm_term": 'utm_term',
        "utm_content": 'utm_content'
    }

    def __init__(self,
                 email=None,
                 tos_consent_date=None,
                 tax_information=None,
                 country_birth=None,
                 last_login=None,
                 successful_referrals=None,
                 kyc_verified=None,
                 is_verified=None,
                 fee_segments=None,
                 portfolios=None,
                 risk_level=None,
                 onboarding_token=None,
                 uuid=None,
                 created=None,
                 updated=None,
                 status=None,
                 language=None,
                 marketing_consent_date=None,
                 data_consent_date=None,
                 birthdate=None,
                 tos_consent=None,
                 marketing_consent=None,
                 data_consent=None,
                 referred_by=None,
                 extra_data=None,
                 onboarded_by=None,
                 password=None,
                 email_verified_last_request=None,
                 comments=None,
                 email_verified=None,
                 email_verify_last_request=None,
                 title=None,
                 first_name=None,
                 middle_name=None,
                 last_name=None,
                 gender=None,
                 marital_status=None,
                 phone_number=None,
                 phone_number_verified=None,
                 employment_status=None,
                 profession=None,
                 referral_code=None,
                 activated=None,
                 utm_source=None,
                 utm_medium=None,
                 utm_campaign=None,
                 utm_term=None,
                 utm_content=None):
        """Constructor for the ApplicationClientUpdate class"""

        # Initialize members of the class
        self.email = email
        self.birthdate = birthdate
        self.tos_consent = tos_consent
        self.marketing_consent = marketing_consent
        self.data_consent = data_consent
        self.tos_consent_date = tos_consent_date
        self.tax_information = tax_information
        self.country_birth = country_birth
        self.last_login = APIHelper.RFC3339DateTime(last_login) if last_login else None
        self.referred_by = referred_by
        self.successful_referrals = successful_referrals
        self.kyc_verified = kyc_verified
        self.is_verified = is_verified
        self.fee_segments = fee_segments
        self.extra_data = extra_data
        self.portfolios = portfolios
        self.onboarded_by = onboarded_by
        self.risk_level = risk_level
        self.onboarding_token = onboarding_token
        self.password = password
        self.email_verified_last_request = APIHelper.RFC3339DateTime(email_verified_last_request) if email_verified_last_request else None
        self.uuid = uuid
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.updated = APIHelper.RFC3339DateTime(updated) if updated else None
        self.comments = comments
        self.status = status
        self.email_verified = email_verified
        self.email_verify_last_request = APIHelper.RFC3339DateTime(email_verify_last_request) if email_verify_last_request else None
        self.title = title
        self.first_name = first_name
        self.middle_name = middle_name
        self.last_name = last_name
        self.gender = gender
        self.marital_status = marital_status
        self.phone_number = phone_number
        self.phone_number_verified = APIHelper.RFC3339DateTime(phone_number_verified) if phone_number_verified else None
        self.language = language
        self.employment_status = employment_status
        self.profession = profession
        self.referral_code = referral_code
        self.activated = APIHelper.RFC3339DateTime(activated) if activated else None
        self.utm_source = utm_source
        self.utm_medium = utm_medium
        self.utm_campaign = utm_campaign
        self.utm_term = utm_term
        self.utm_content = utm_content
        self.marketing_consent_date = marketing_consent_date
        self.data_consent_date = data_consent_date

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        email = dictionary.get('email')
        tos_consent_date = dateutil.parser.parse(dictionary.get('tos_consent_date')).date() if dictionary.get('tos_consent_date') else None
        tax_information = dictionary.get('tax_information')
        country_birth = CountryField.from_dictionary(dictionary.get('country_birth')) if dictionary.get('country_birth') else None
        last_login = APIHelper.RFC3339DateTime.from_value(dictionary.get("last_login")).datetime if dictionary.get("last_login") else None
        successful_referrals = dictionary.get('successful_referrals')
        kyc_verified = dictionary.get('kyc_verified')
        is_verified = dictionary.get('is_verified')
        fee_segments = dictionary.get('fee_segments')
        portfolios = dictionary.get('portfolios')
        risk_level = dictionary.get('risk_level')
        onboarding_token = dictionary.get('onboarding_token')
        uuid = dictionary.get('uuid')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        updated = APIHelper.RFC3339DateTime.from_value(dictionary.get("updated")).datetime if dictionary.get("updated") else None
        status = dictionary.get('status')
        language = dictionary.get('language')
        marketing_consent_date = dateutil.parser.parse(dictionary.get('marketing_consent_date')).date() if dictionary.get('marketing_consent_date') else None
        data_consent_date = dateutil.parser.parse(dictionary.get('data_consent_date')).date() if dictionary.get('data_consent_date') else None
        birthdate = dateutil.parser.parse(dictionary.get('birthdate')).date() if dictionary.get('birthdate') else None
        tos_consent = dictionary.get('tos_consent')
        marketing_consent = dictionary.get('marketing_consent')
        data_consent = dictionary.get('data_consent')
        referred_by = dictionary.get('referred_by')
        extra_data = dictionary.get('extra_data')
        onboarded_by = dictionary.get('onboarded_by')
        password = dictionary.get('password')
        email_verified_last_request = APIHelper.RFC3339DateTime.from_value(dictionary.get("email_verified_last_request")).datetime if dictionary.get("email_verified_last_request") else None
        comments = dictionary.get('comments')
        email_verified = dictionary.get('email_verified')
        email_verify_last_request = APIHelper.RFC3339DateTime.from_value(dictionary.get("email_verify_last_request")).datetime if dictionary.get("email_verify_last_request") else None
        title = dictionary.get('title')
        first_name = dictionary.get('first_name')
        middle_name = dictionary.get('middle_name')
        last_name = dictionary.get('last_name')
        gender = dictionary.get('gender')
        marital_status = dictionary.get('marital_status')
        phone_number = dictionary.get('phone_number')
        phone_number_verified = APIHelper.RFC3339DateTime.from_value(dictionary.get("phone_number_verified")).datetime if dictionary.get("phone_number_verified") else None
        employment_status = dictionary.get('employment_status')
        profession = dictionary.get('profession')
        referral_code = dictionary.get('referral_code')
        activated = APIHelper.RFC3339DateTime.from_value(dictionary.get("activated")).datetime if dictionary.get("activated") else None
        utm_source = dictionary.get('utm_source')
        utm_medium = dictionary.get('utm_medium')
        utm_campaign = dictionary.get('utm_campaign')
        utm_term = dictionary.get('utm_term')
        utm_content = dictionary.get('utm_content')

        # Return an object of this model
        return cls(email,
                   tos_consent_date,
                   tax_information,
                   country_birth,
                   last_login,
                   successful_referrals,
                   kyc_verified,
                   is_verified,
                   fee_segments,
                   portfolios,
                   risk_level,
                   onboarding_token,
                   uuid,
                   created,
                   updated,
                   status,
                   language,
                   marketing_consent_date,
                   data_consent_date,
                   birthdate,
                   tos_consent,
                   marketing_consent,
                   data_consent,
                   referred_by,
                   extra_data,
                   onboarded_by,
                   password,
                   email_verified_last_request,
                   comments,
                   email_verified,
                   email_verify_last_request,
                   title,
                   first_name,
                   middle_name,
                   last_name,
                   gender,
                   marital_status,
                   phone_number,
                   phone_number_verified,
                   employment_status,
                   profession,
                   referral_code,
                   activated,
                   utm_source,
                   utm_medium,
                   utm_campaign,
                   utm_term,
                   utm_content)
