# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AssetCategory(object):

    """Implementation of the 'AssetCategory' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        name (string): TODO: type description here.
        code (string): TODO: type description here.
        order (int): TODO: type description here.
        mtype (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "name": 'name',
        "code": 'code',
        "order": 'order',
        "mtype": 'type'
    }

    def __init__(self,
                 uuid=None,
                 name=None,
                 code=None,
                 order=None,
                 mtype=None):
        """Constructor for the AssetCategory class"""

        # Initialize members of the class
        self.uuid = uuid
        self.name = name
        self.code = code
        self.order = order
        self.mtype = mtype

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        name = dictionary.get('name')
        code = dictionary.get('code')
        order = dictionary.get('order')
        mtype = dictionary.get('type')

        # Return an object of this model
        return cls(uuid,
                   name,
                   code,
                   order,
                   mtype)
