# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AssetGrowth(object):

    """Implementation of the 'AssetGrowth' model.

    TODO: type model description here.

    Attributes:
        year (int): TODO: type description here.
        amount (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "year": 'year',
        "amount": 'amount'
    }

    def __init__(self,
                 year=None,
                 amount=None):
        """Constructor for the AssetGrowth class"""

        # Initialize members of the class
        self.year = year
        self.amount = amount

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        year = dictionary.get('year')
        amount = dictionary.get('amount')

        # Return an object of this model
        return cls(year,
                   amount)
