# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AssetTypeEnum(object):

    """Implementation of the 'AssetTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        ETF: TODO: type description here.
        MUTUAL_FUND: TODO: type description here.
        STOCK: TODO: type description here.

    """

    ETF = 'ETF'

    MUTUAL_FUND = 'MUTUAL_FUND'

    STOCK = 'STOCK'
