# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.models.asset_category import AssetCategory


class AssetList(object):

    """Implementation of the 'AssetList' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        uuid (uuid|string): TODO: type description here.
        name (string): TODO: type description here.
        isin (string): TODO: type description here.
        ticker (string): TODO: type description here.
        status (Status6f6Enum): TODO: type description here.
        market (string): TODO: type description here.
        currency (string): TODO: type description here.
        extra_data (dict): TODO: type description here.
        categories (list of AssetCategory): TODO: type description here.
        asset_type (AssetTypeEnum): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "name": 'name',
        "isin": 'isin',
        "ticker": 'ticker',
        "status": 'status',
        "market": 'market',
        "currency": 'currency',
        "extra_data": 'extra_data',
        "categories": 'categories',
        "asset_type": 'asset_type'
    }

    def __init__(self,
                 uuid=None,
                 name=None,
                 isin=None,
                 ticker=None,
                 status=None,
                 market=None,
                 currency=None,
                 extra_data=None,
                 categories=None,
                 asset_type=None):
        """Constructor for the AssetList class"""

        # Initialize members of the class
        self.uuid = uuid
        self.name = name
        self.isin = isin
        self.ticker = ticker
        self.status = status
        self.market = market
        self.currency = currency
        self.extra_data = extra_data
        self.categories = categories
        self.asset_type = asset_type

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        name = dictionary.get('name')
        isin = dictionary.get('isin')
        ticker = dictionary.get('ticker')
        status = dictionary.get('status')
        market = dictionary.get('market')
        currency = dictionary.get('currency')
        extra_data = dictionary.get('extra_data')
        categories = None
        if dictionary.get('categories') is not None:
            categories = [AssetCategory.from_dictionary(x) for x in dictionary.get('categories')]
        asset_type = dictionary.get('asset_type')

        # Return an object of this model
        return cls(uuid,
                   name,
                   isin,
                   ticker,
                   status,
                   market,
                   currency,
                   extra_data,
                   categories,
                   asset_type)
