# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AssessmentStatusEnum(object):

    """Implementation of the 'AssessmentStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        COMPLETED: TODO: type description here.
        OUTDATED: TODO: type description here.

    """

    PENDING = 'PENDING'

    COMPLETED = 'COMPLETED'

    OUTDATED = 'OUTDATED'
