# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class AUMPortfolioRisk(object):

    """Implementation of the 'AUMPortfolioRisk' model.

    TODO: type model description here.

    Attributes:
        risk_level (int): TODO: type description here.
        balance (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "risk_level": 'risk_level',
        "balance": 'balance'
    }

    def __init__(self,
                 risk_level=None,
                 balance=None):
        """Constructor for the AUMPortfolioRisk class"""

        # Initialize members of the class
        self.risk_level = risk_level
        self.balance = balance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        risk_level = dictionary.get('risk_level')
        balance = dictionary.get('balance')

        # Return an object of this model
        return cls(risk_level,
                   balance)
