# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.models.asset_category import AssetCategory


class Category(object):

    """Implementation of the 'Category' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        code (string): TODO: type description here.
        categories (list of AssetCategory): TODO: type description here.
        name (string): TODO: type description here.
        status (CategoryStatusEnum): TODO: type description here.
        extra_data (dict): Additional ETSCategory attributes
        description (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "code": 'code',
        "categories": 'categories',
        "name": 'name',
        "status": 'status',
        "extra_data": 'extra_data',
        "description": 'description'
    }

    def __init__(self,
                 uuid=None,
                 code=None,
                 categories=None,
                 name=None,
                 status=None,
                 extra_data=None,
                 description=None):
        """Constructor for the Category class"""

        # Initialize members of the class
        self.uuid = uuid
        self.code = code
        self.categories = categories
        self.name = name
        self.status = status
        self.extra_data = extra_data
        self.description = description

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        code = dictionary.get('code')
        categories = None
        if dictionary.get('categories') is not None:
            categories = [AssetCategory.from_dictionary(x) for x in dictionary.get('categories')]
        name = dictionary.get('name')
        status = dictionary.get('status')
        extra_data = dictionary.get('extra_data')
        description = dictionary.get('description')

        # Return an object of this model
        return cls(uuid,
                   code,
                   categories,
                   name,
                   status,
                   extra_data,
                   description)
