# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CategoryStatusEnum(object):

    """Implementation of the 'CategoryStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.

    """

    ACTIVE = 'ACTIVE'

    INACTIVE = 'INACTIVE'
