# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ChannelEnum(object):

    """Implementation of the 'ChannelEnum' enum.

    TODO: type enum description here.

    Attributes:
        BROWSER: TODO: type description here.
        IOS: TODO: type description here.
        ANDROID: TODO: type description here.

    """

    BROWSER = 'BROWSER'

    IOS = 'IOS'

    ANDROID = 'ANDROID'
