# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ClientReferral(object):

    """Implementation of the 'ClientReferral' model.

    TODO: type model description here.

    Attributes:
        first_name (string): TODO: type description here.
        last_name (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "first_name": 'first_name',
        "last_name": 'last_name'
    }

    def __init__(self,
                 first_name=None,
                 last_name=None):
        """Constructor for the ClientReferral class"""

        # Initialize members of the class
        self.first_name = first_name
        self.last_name = last_name

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        first_name = dictionary.get('first_name')
        last_name = dictionary.get('last_name')

        # Return an object of this model
        return cls(first_name,
                   last_name)
