# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser


class ClientPerformance(object):

    """Implementation of the 'ClientPerformance' model.

    TODO: type model description here.

    Attributes:
        valuation_date (date): TODO: type description here.
        performance (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "valuation_date": 'valuation_date',
        "performance": 'performance'
    }

    def __init__(self,
                 valuation_date=None,
                 performance=None):
        """Constructor for the ClientPerformance class"""

        # Initialize members of the class
        self.valuation_date = valuation_date
        self.performance = performance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        valuation_date = dateutil.parser.parse(dictionary.get('valuation_date')).date() if dictionary.get('valuation_date') else None
        performance = dictionary.get('performance')

        # Return an object of this model
        return cls(valuation_date,
                   performance)
