# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper
from nucoroapiv2.models.message import Message


class ConversationCreate(object):

    """Implementation of the 'ConversationCreate' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        portal (int): TODO: type description here.
        created (datetime): TODO: type description here.
        subject (string): TODO: type description here.
        messages (Message): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "portal": 'portal',
        "created": 'created',
        "subject": 'subject',
        "messages": 'messages'
    }

    def __init__(self,
                 uuid=None,
                 portal=None,
                 created=None,
                 subject=None,
                 messages=None):
        """Constructor for the ConversationCreate class"""

        # Initialize members of the class
        self.uuid = uuid
        self.portal = portal
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.subject = subject
        self.messages = messages

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        portal = dictionary.get('portal')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        subject = dictionary.get('subject')
        messages = Message.from_dictionary(dictionary.get('messages')) if dictionary.get('messages') else None

        # Return an object of this model
        return cls(uuid,
                   portal,
                   created,
                   subject,
                   messages)
