# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CountryField(object):

    """Implementation of the 'CountryField' model.

    TODO: type model description here.

    Attributes:
        id (int): TODO: type description here.
        code (string): TODO: type description here.
        iso_3 (string): TODO: type description here.
        name (string): TODO: type description here.
        name_en_gb (string): TODO: type description here.
        name_en_ch (string): TODO: type description here.
        name_fr_ch (string): TODO: type description here.
        long_name (string): TODO: type description here.
        long_name_en_gb (string): TODO: type description here.
        long_name_en_ch (string): TODO: type description here.
        long_name_fr_ch (string): TODO: type description here.
        eea_country (bool): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "code": 'code',
        "iso_3": 'iso3',
        "name": 'name',
        "long_name": 'long_name',
        "name_en_gb": 'name_en_gb',
        "name_en_ch": 'name_en_ch',
        "name_fr_ch": 'name_fr_ch',
        "long_name_en_gb": 'long_name_en_gb',
        "long_name_en_ch": 'long_name_en_ch',
        "long_name_fr_ch": 'long_name_fr_ch',
        "eea_country": 'eea_country'
    }

    def __init__(self,
                 id=None,
                 code=None,
                 iso_3=None,
                 name=None,
                 long_name=None,
                 name_en_gb=None,
                 name_en_ch=None,
                 name_fr_ch=None,
                 long_name_en_gb=None,
                 long_name_en_ch=None,
                 long_name_fr_ch=None,
                 eea_country=None):
        """Constructor for the CountryField class"""

        # Initialize members of the class
        self.id = id
        self.code = code
        self.iso_3 = iso_3
        self.name = name
        self.name_en_gb = name_en_gb
        self.name_en_ch = name_en_ch
        self.name_fr_ch = name_fr_ch
        self.long_name = long_name
        self.long_name_en_gb = long_name_en_gb
        self.long_name_en_ch = long_name_en_ch
        self.long_name_fr_ch = long_name_fr_ch
        self.eea_country = eea_country

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        code = dictionary.get('code')
        iso_3 = dictionary.get('iso3')
        name = dictionary.get('name')
        long_name = dictionary.get('long_name')
        name_en_gb = dictionary.get('name_en_gb')
        name_en_ch = dictionary.get('name_en_ch')
        name_fr_ch = dictionary.get('name_fr_ch')
        long_name_en_gb = dictionary.get('long_name_en_gb')
        long_name_en_ch = dictionary.get('long_name_en_ch')
        long_name_fr_ch = dictionary.get('long_name_fr_ch')
        eea_country = dictionary.get('eea_country')

        # Return an object of this model
        return cls(id,
                   code,
                   iso_3,
                   name,
                   long_name,
                   name_en_gb,
                   name_en_ch,
                   name_fr_ch,
                   long_name_en_gb,
                   long_name_en_ch,
                   long_name_fr_ch,
                   eea_country)
