# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class CreateOrderMethodEnum(object):

    """Implementation of the 'CreateOrderMethodEnum' enum.

    TODO: type enum description here.

    Attributes:
        MARKET: TODO: type description here.
        STOP: TODO: type description here.
        LIMIT: TODO: type description here.

    """

    MARKET = 'MARKET'

    STOP = 'STOP'

    LIMIT = 'LIMIT'
