# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Currency(object):

    """Implementation of the 'Currency' model.

    TODO: type model description here.

    Attributes:
        code (string): TODO: type description here.
        name (string): TODO: type description here.
        symbol (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": 'code',
        "name": 'name',
        "symbol": 'symbol'
    }

    def __init__(self,
                 code=None,
                 name=None,
                 symbol=None):
        """Constructor for the Currency class"""

        # Initialize members of the class
        self.code = code
        self.name = name
        self.symbol = symbol

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        code = dictionary.get('code')
        name = dictionary.get('name')
        symbol = dictionary.get('symbol')

        # Return an object of this model
        return cls(code,
                   name,
                   symbol)
