# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DepositTypeEnum(object):

    """Implementation of the 'DepositTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        CONTRIBUTION: TODO: type description here.
        TRANSFER: TODO: type description here.

    """

    CONTRIBUTION = 'CONTRIBUTION'

    TRANSFER = 'TRANSFER'
