# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class DepositList(object):

    """Implementation of the 'DepositList' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        amount (float): TODO: type description here.
        reference (string): TODO: type description here.
        status (StatusB6aEnum): TODO: type description here.
        deposit_type (DepositTypeEnum): TODO: type description here.
        completed (datetime): TODO: type description here.
        transacted_at (datetime): TODO: type description here.
        extra_data (dict): Additional deposit attributes for the specific
            portal

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "amount": 'amount',
        "reference": 'reference',
        "status": 'status',
        "deposit_type": 'deposit_type',
        "completed": 'completed',
        "transacted_at": 'transacted_at',
        "extra_data": 'extra_data'
    }

    def __init__(self,
                 uuid=None,
                 amount=None,
                 reference=None,
                 status=None,
                 deposit_type=None,
                 completed=None,
                 transacted_at=None,
                 extra_data=None):
        """Constructor for the DepositList class"""

        # Initialize members of the class
        self.uuid = uuid
        self.amount = amount
        self.reference = reference
        self.status = status
        self.deposit_type = deposit_type
        self.completed = APIHelper.RFC3339DateTime(completed) if completed else None
        self.transacted_at = APIHelper.RFC3339DateTime(transacted_at) if transacted_at else None
        self.extra_data = extra_data

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        amount = dictionary.get('amount')
        reference = dictionary.get('reference')
        status = dictionary.get('status')
        deposit_type = dictionary.get('deposit_type')
        completed = APIHelper.RFC3339DateTime.from_value(dictionary.get("completed")).datetime if dictionary.get("completed") else None
        transacted_at = APIHelper.RFC3339DateTime.from_value(dictionary.get("transacted_at")).datetime if dictionary.get("transacted_at") else None
        extra_data = dictionary.get('extra_data')

        # Return an object of this model
        return cls(uuid,
                   amount,
                   reference,
                   status,
                   deposit_type,
                   completed,
                   transacted_at,
                   extra_data)
