# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DocTypeEnum(object):

    """Implementation of the 'DocTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        ID_PERSONAL: TODO: type description here.
        BANK_DETAILS: TODO: type description here.
        EMPLOYMENT: TODO: type description here.
        MARITAL_STATUS: TODO: type description here.
        PENSION: TODO: type description here.
        LEGAL: TODO: type description here.
        TRANSFERS: TODO: type description here.
        MEDICAL: TODO: type description here.
        CONTRACT: TODO: type description here.
        OTHERS: TODO: type description here.

    """

    ID_PERSONAL = 'ID_PERSONAL'

    BANK_DETAILS = 'BANK_DETAILS'

    EMPLOYMENT = 'EMPLOYMENT'

    MARITAL_STATUS = 'MARITAL_STATUS'

    PENSION = 'PENSION'

    LEGAL = 'LEGAL'

    TRANSFERS = 'TRANSFERS'

    MEDICAL = 'MEDICAL'

    CONTRACT = 'CONTRACT'

    OTHERS = 'OTHERS'
