# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DocumentTypeEnum(object):

    """Implementation of the 'DocumentTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        PASSPORT: TODO: type description here.
        DRIVING_LICENCE: TODO: type description here.
        NATIONAL_IDENTITY_CARD: TODO: type description here.
        UTILITY_BILL: TODO: type description here.
        LOCAL_TAX_BILL: TODO: type description here.
        BANK_STATEMENT: TODO: type description here.
        LEASE_AGREEMENT: TODO: type description here.
        RENT_RECEIPT: TODO: type description here.
        LETTER: TODO: type description here.
        CERTIFICATE_MARRIAGE: TODO: type description here.
        DECREE_ABSOLUTE: TODO: type description here.
        FINAL_ORDER: TODO: type description here.
        CLIENT_PHOTO: TODO: type description here.

    """

    PASSPORT = 'passport'

    DRIVING_LICENCE = 'driving_licence'

    NATIONAL_IDENTITY_CARD = 'national_identity_card'

    UTILITY_BILL = 'utility_bill'

    LOCAL_TAX_BILL = 'local_tax_bill'

    BANK_STATEMENT = 'bank_statement'

    LEASE_AGREEMENT = 'lease_agreement'

    RENT_RECEIPT = 'rent_receipt'

    LETTER = 'letter'

    CERTIFICATE_MARRIAGE = 'certificate_marriage'

    DECREE_ABSOLUTE = 'decree_absolute'

    FINAL_ORDER = 'final_order'

    CLIENT_PHOTO = 'client_photo'
