# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class DurationEnum(object):

    """Implementation of the 'DurationEnum' enum.

    TODO: type enum description here.

    Attributes:
        GOOD_TILL_CANCEL: TODO: type description here.
        DAY_ORDER: TODO: type description here.

    """

    GOOD_TILL_CANCEL = 'GOOD_TILL_CANCEL'

    DAY_ORDER = 'DAY_ORDER'
