# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class EmploymentStatusEnum(object):

    """Implementation of the 'EmploymentStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        EMPLOYED: TODO: type description here.
        SELF_EMPLOYED: TODO: type description here.
        RETIRED: TODO: type description here.
        UNEMPLOYED: TODO: type description here.

    """

    EMPLOYED = 'EMPLOYED'

    SELF_EMPLOYED = 'SELF_EMPLOYED'

    RETIRED = 'RETIRED'

    UNEMPLOYED = 'UNEMPLOYED'
