# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ETSForecastRequest(object):

    """Implementation of the 'ETSForecastRequest' model.

    TODO: type model description here.

    Attributes:
        time_horizon (int): TODO: type description here.
        initial_amount (float): TODO: type description here.
        recurring_amount (float): TODO: type description here.
        recurring_period (int): TODO: type description here.
        risk_level (int): TODO: type description here.
        favourite_categories (list of string): TODO: type description here.
        excluded_categories (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "time_horizon": 'time_horizon',
        "initial_amount": 'initial_amount',
        "risk_level": 'risk_level',
        "recurring_amount": 'recurring_amount',
        "recurring_period": 'recurring_period',
        "favourite_categories": 'favourite_categories',
        "excluded_categories": 'excluded_categories'
    }

    def __init__(self,
                 time_horizon=None,
                 initial_amount=None,
                 risk_level=None,
                 recurring_amount=None,
                 recurring_period=None,
                 favourite_categories=None,
                 excluded_categories=None):
        """Constructor for the ETSForecastRequest class"""

        # Initialize members of the class
        self.time_horizon = time_horizon
        self.initial_amount = initial_amount
        self.recurring_amount = recurring_amount
        self.recurring_period = recurring_period
        self.risk_level = risk_level
        self.favourite_categories = favourite_categories
        self.excluded_categories = excluded_categories

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        time_horizon = dictionary.get('time_horizon')
        initial_amount = dictionary.get('initial_amount')
        risk_level = dictionary.get('risk_level')
        recurring_amount = dictionary.get('recurring_amount')
        recurring_period = dictionary.get('recurring_period')
        favourite_categories = dictionary.get('favourite_categories')
        excluded_categories = dictionary.get('excluded_categories')

        # Return an object of this model
        return cls(time_horizon,
                   initial_amount,
                   risk_level,
                   recurring_amount,
                   recurring_period,
                   favourite_categories,
                   excluded_categories)
