# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FeeTypeEnum(object):

    """Implementation of the 'FeeTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        PORTAL_SERVICE: TODO: type description here.
        SELLER_FEE: TODO: type description here.

    """

    PORTAL_SERVICE = 'portal_service'

    SELLER_FEE = 'seller_fee'
