# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser


class ForecastRequest(object):

    """Implementation of the 'ForecastRequest' model.

    TODO: type model description here.

    Attributes:
        goal_amount (float): TODO: type description here.
        deadline (date): TODO: type description here.
        initial_amount (float): TODO: type description here.
        recurring_amount (float): TODO: type description here.
        risk_level (int): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "goal_amount": 'goal_amount',
        "deadline": 'deadline',
        "initial_amount": 'initial_amount',
        "recurring_amount": 'recurring_amount',
        "risk_level": 'risk_level'
    }

    def __init__(self,
                 goal_amount=None,
                 deadline=None,
                 initial_amount=None,
                 recurring_amount=None,
                 risk_level=None):
        """Constructor for the ForecastRequest class"""

        # Initialize members of the class
        self.goal_amount = goal_amount
        self.deadline = deadline
        self.initial_amount = initial_amount
        self.recurring_amount = recurring_amount
        self.risk_level = risk_level

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        goal_amount = dictionary.get('goal_amount')
        deadline = dateutil.parser.parse(dictionary.get('deadline')).date() if dictionary.get('deadline') else None
        initial_amount = dictionary.get('initial_amount')
        recurring_amount = dictionary.get('recurring_amount')
        risk_level = dictionary.get('risk_level')

        # Return an object of this model
        return cls(goal_amount,
                   deadline,
                   initial_amount,
                   recurring_amount,
                   risk_level)
