# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Format1Enum(object):

    """Implementation of the 'format1' enum.

    TODO: type enum description here.

    Attributes:
        BASE64: TODO: type description here.
        JSON: TODO: type description here.
        PDF: TODO: type description here.

    """

    BASE64 = 'base64'

    JSON = 'json'

    PDF = 'pdf'
