# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class FormatEnum(object):

    """Implementation of the 'format' enum.

    TODO: type enum description here.

    Attributes:
        JSON: TODO: type description here.
        YAML: TODO: type description here.

    """

    JSON = 'json'

    YAML = 'yaml'
