# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class GenderEnum(object):

    """Implementation of the 'GenderEnum' enum.

    TODO: type enum description here.

    Attributes:
        M: TODO: type description here.
        F: TODO: type description here.
        U: TODO: type description here.

    """

    M = 'M'

    F = 'F'

    U = 'U'
