# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser

from nucoroapiv2.api_helper import APIHelper


class InvoiceDetails(object):

    """Implementation of the 'InvoiceDetails' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        uuid (uuid|string): TODO: type description here.
        number (string): Invoice legal number
        status (Status260Enum): TODO: type description here.
        created (datetime): TODO: type description here.
        date_from (date): Beginning of charge period
        date_to (date): End of charge period
        url (string): TODO: type description here.
        amount (float): TODO: type description here.
        charges (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "created": 'created',
        "url": 'url',
        "amount": 'amount',
        "charges": 'charges',
        "number": 'number',
        "status": 'status',
        "date_from": 'date_from',
        "date_to": 'date_to'
    }

    def __init__(self,
                 uuid=None,
                 created=None,
                 url=None,
                 amount=None,
                 charges=None,
                 number=None,
                 status=None,
                 date_from=None,
                 date_to=None):
        """Constructor for the InvoiceDetails class"""

        # Initialize members of the class
        self.uuid = uuid
        self.number = number
        self.status = status
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.date_from = date_from
        self.date_to = date_to
        self.url = url
        self.amount = amount
        self.charges = charges

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        url = dictionary.get('url')
        amount = dictionary.get('amount')
        charges = dictionary.get('charges')
        number = dictionary.get('number')
        status = dictionary.get('status')
        date_from = dateutil.parser.parse(dictionary.get('date_from')).date() if dictionary.get('date_from') else None
        date_to = dateutil.parser.parse(dictionary.get('date_to')).date() if dictionary.get('date_to') else None

        # Return an object of this model
        return cls(uuid,
                   created,
                   url,
                   amount,
                   charges,
                   number,
                   status,
                   date_from,
                   date_to)
