# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class JSONWebToken(object):

    """Implementation of the 'JSONWebToken' model.

    TODO: type model description here.

    Attributes:
        username (string): TODO: type description here.
        password (string): TODO: type description here.
        captcha (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "username": 'username',
        "password": 'password',
        "captcha": 'captcha'
    }

    def __init__(self,
                 username=None,
                 password=None,
                 captcha=None):
        """Constructor for the JSONWebToken class"""

        # Initialize members of the class
        self.username = username
        self.password = password
        self.captcha = captcha

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        username = dictionary.get('username')
        password = dictionary.get('password')
        captcha = dictionary.get('captcha')

        # Return an object of this model
        return cls(username,
                   password,
                   captcha)
