# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class JWTRefreshResponse(object):

    """Implementation of the 'JWTRefreshResponse' model.

    TODO: type model description here.

    Attributes:
        access (string): TODO: type description here.
        refresh (string): TODO: type description here.
        status (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "access": 'access',
        "refresh": 'refresh',
        "status": 'status'
    }

    def __init__(self,
                 access=None,
                 refresh=None,
                 status=None):
        """Constructor for the JWTRefreshResponse class"""

        # Initialize members of the class
        self.access = access
        self.refresh = refresh
        self.status = status

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        access = dictionary.get('access')
        refresh = dictionary.get('refresh')
        status = dictionary.get('status')

        # Return an object of this model
        return cls(access,
                   refresh,
                   status)
