# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class LangEnum(object):

    """Implementation of the 'lang' enum.

    TODO: type enum description here.

    Attributes:
        ENCH: TODO: type description here.
        ENGB: TODO: type description here.
        FRCH: TODO: type description here.

    """

    ENCH = 'en-ch'

    ENGB = 'en-gb'

    FRCH = 'fr-ch'
