# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class MaritalStatusEnum(object):

    """Implementation of the 'MaritalStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        NOT_DISCLOSED: TODO: type description here.
        SINGLE: TODO: type description here.
        MARRIED_CIVIL_PARTNER: TODO: type description here.
        CIVIL_PARTNER: TODO: type description here.
        DIVORCED_DISSOLVED_CIVIL_PARTNERSHIP: TODO: type description here.
        WIDOWED_SURVIVING_CIVIL_PARTNER: TODO: type description here.
        SEPARATED: TODO: type description here.

    """

    NOT_DISCLOSED = 'NOT_DISCLOSED'

    SINGLE = 'SINGLE'

    MARRIED_CIVIL_PARTNER = 'MARRIED_CIVIL_PARTNER'

    CIVIL_PARTNER = 'CIVIL_PARTNER'

    DIVORCED_DISSOLVED_CIVIL_PARTNERSHIP = 'DIVORCED_DISSOLVED_CIVIL_PARTNERSHIP'

    WIDOWED_SURVIVING_CIVIL_PARTNER = 'WIDOWED_SURVIVING_CIVIL_PARTNER'

    SEPARATED = 'SEPARATED'
