# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NationalityList(object):

    """Implementation of the 'NationalityList' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        uuid (uuid|string): TODO: type description here.
        country (string): TODO: type description here.
        document_type (string): TODO: type description here.
        document_number (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "country": 'country',
        "document_number": 'document_number',
        "document_type": 'document_type'
    }

    def __init__(self,
                 uuid=None,
                 country=None,
                 document_number=None,
                 document_type=None):
        """Constructor for the NationalityList class"""

        # Initialize members of the class
        self.uuid = uuid
        self.country = country
        self.document_type = document_type
        self.document_number = document_number

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        country = dictionary.get('country')
        document_number = dictionary.get('document_number')
        document_type = dictionary.get('document_type')

        # Return an object of this model
        return cls(uuid,
                   country,
                   document_number,
                   document_type)
