# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NationalDocument(object):

    """Implementation of the 'NationalDocument' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        code (string): TODO: type description here.
        name (string): TODO: type description here.
        countries (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "code": 'code',
        "name": 'name',
        "countries": 'countries'
    }

    def __init__(self,
                 uuid=None,
                 code=None,
                 name=None,
                 countries=None):
        """Constructor for the NationalDocument class"""

        # Initialize members of the class
        self.uuid = uuid
        self.code = code
        self.name = name
        self.countries = countries

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        code = dictionary.get('code')
        name = dictionary.get('name')
        countries = dictionary.get('countries')

        # Return an object of this model
        return cls(uuid,
                   code,
                   name,
                   countries)
