# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class NucoroSetting(object):

    """Implementation of the 'NucoroSetting' model.

    TODO: type model description here.

    Attributes:
        key (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "key": 'key'
    }

    def __init__(self,
                 key=None):
        """Constructor for the NucoroSetting class"""

        # Initialize members of the class
        self.key = key

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        key = dictionary.get('key')

        # Return an object of this model
        return cls(key)
