# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderingEnum(object):

    """Implementation of the 'ordering' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_ACTIVATED: TODO: type description here.
        ENUM_CREATED: TODO: type description here.
        ENUM_FIRST_NAME: TODO: type description here.
        ENUM_LAST_NAME: TODO: type description here.
        ENUM_RISK_LEVEL: TODO: type description here.
        ENUM_STATUS: TODO: type description here.
        ACTIVATED: TODO: type description here.
        CREATED: TODO: type description here.
        FIRST_NAME: TODO: type description here.
        LAST_NAME: TODO: type description here.
        RISK_LEVEL: TODO: type description here.
        STATUS: TODO: type description here.

    """

    ENUM_ACTIVATED = '-activated'

    ENUM_CREATED = '-created'

    ENUM_FIRST_NAME = '-first_name'

    ENUM_LAST_NAME = '-last_name'

    ENUM_RISK_LEVEL = '-risk_level'

    ENUM_STATUS = '-status'

    ACTIVATED = 'activated'

    CREATED = 'created'

    FIRST_NAME = 'first_name'

    LAST_NAME = 'last_name'

    RISK_LEVEL = 'risk_level'

    STATUS = 'status'
