# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderTypeEnum(object):

    """Implementation of the 'OrderTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        BUY: TODO: type description here.
        SELL: TODO: type description here.
        VERIFICATION: TODO: type description here.

    """

    BUY = 'BUY'

    SELL = 'SELL'

    VERIFICATION = 'VERIFICATION'
