# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderListMethodEnum(object):

    """Implementation of the 'OrderListMethodEnum' enum.

    TODO: type enum description here.

    Attributes:
        MARKET: TODO: type description here.
        QUOTE: TODO: type description here.
        INTERNAL: TODO: type description here.
        LIMIT: TODO: type description here.
        STOP: TODO: type description here.

    """

    MARKET = 'MARKET'

    QUOTE = 'QUOTE'

    INTERNAL = 'INTERNAL'

    LIMIT = 'LIMIT'

    STOP = 'STOP'
