# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class OrderListStatusEnum(object):

    """Implementation of the 'OrderListStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        WAITING_FOR_PRICE: TODO: type description here.
        PROCESSING: TODO: type description here.
        QUOTED: TODO: type description here.
        COMPLETED: TODO: type description here.
        VERIFIED: TODO: type description here.
        ERROR: TODO: type description here.
        CANCELLED: TODO: type description here.

    """

    PENDING = 'PENDING'

    WAITING_FOR_PRICE = 'WAITING_FOR_PRICE'

    PROCESSING = 'PROCESSING'

    QUOTED = 'QUOTED'

    COMPLETED = 'COMPLETED'

    VERIFIED = 'VERIFIED'

    ERROR = 'ERROR'

    CANCELLED = 'CANCELLED'
