# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PasswordUpdate(object):

    """Implementation of the 'PasswordUpdate' model.

    TODO: type model description here.

    Attributes:
        old_password (string): TODO: type description here.
        new_password (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "new_password": 'new_password',
        "old_password": 'old_password'
    }

    def __init__(self,
                 new_password=None,
                 old_password=None):
        """Constructor for the PasswordUpdate class"""

        # Initialize members of the class
        self.old_password = old_password
        self.new_password = new_password

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        new_password = dictionary.get('new_password')
        old_password = dictionary.get('old_password')

        # Return an object of this model
        return cls(new_password,
                   old_password)
