# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser

from nucoroapiv2.api_helper import APIHelper


class PatchedGoal(object):

    """Implementation of the 'PatchedGoal' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        name (string): TODO: type description here.
        portfolio (string): TODO: type description here.
        goal_amount (float): Desired amount needed to fulfill the goal
        deadline (date): Due date to reach the goal.
        initial_amount (float): Initial deposit amount to start from. No sense
            to start by 0
        recurring_amount (float): TODO: type description here.
        risk_level (int): TODO: type description here.
        created (datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "name": 'name',
        "portfolio": 'portfolio',
        "goal_amount": 'goal_amount',
        "deadline": 'deadline',
        "initial_amount": 'initial_amount',
        "recurring_amount": 'recurring_amount',
        "risk_level": 'risk_level',
        "created": 'created'
    }

    def __init__(self,
                 uuid=None,
                 name=None,
                 portfolio=None,
                 goal_amount=None,
                 deadline=None,
                 initial_amount=None,
                 recurring_amount=None,
                 risk_level=None,
                 created=None):
        """Constructor for the PatchedGoal class"""

        # Initialize members of the class
        self.uuid = uuid
        self.name = name
        self.portfolio = portfolio
        self.goal_amount = goal_amount
        self.deadline = deadline
        self.initial_amount = initial_amount
        self.recurring_amount = recurring_amount
        self.risk_level = risk_level
        self.created = APIHelper.RFC3339DateTime(created) if created else None

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        name = dictionary.get('name')
        portfolio = dictionary.get('portfolio')
        goal_amount = dictionary.get('goal_amount')
        deadline = dateutil.parser.parse(dictionary.get('deadline')).date() if dictionary.get('deadline') else None
        initial_amount = dictionary.get('initial_amount')
        recurring_amount = dictionary.get('recurring_amount')
        risk_level = dictionary.get('risk_level')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None

        # Return an object of this model
        return cls(uuid,
                   name,
                   portfolio,
                   goal_amount,
                   deadline,
                   initial_amount,
                   recurring_amount,
                   risk_level,
                   created)
