# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class PortfolioDetail(object):

    """Implementation of the 'PortfolioDetail' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        uuid (uuid|string): TODO: type description here.
        name (string): TODO: type description here.
        portfolio_type (string): TODO: type description here.
        risk_level (int): TODO: type description here.
        time_horizon (int): TODO: type description here.
        status (Status2efEnum): TODO: type description here.
        extra_data (dict): Additional Portfolio attributes
        currency (string): TODO: type description here.
        created (datetime): TODO: type description here.
        activated (datetime): TODO: type description here.
        balance (float): TODO: type description here.
        performance (float): TODO: type description here.
        deposit_reference (string): TODO: type description here.
        advisor (string): TODO: type description here.
        advice_engine (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "name": 'name',
        "portfolio_type": 'portfolio_type',
        "created": 'created',
        "balance": 'balance',
        "performance": 'performance',
        "deposit_reference": 'deposit_reference',
        "risk_level": 'risk_level',
        "time_horizon": 'time_horizon',
        "status": 'status',
        "extra_data": 'extra_data',
        "currency": 'currency',
        "activated": 'activated',
        "advisor": 'advisor',
        "advice_engine": 'advice_engine'
    }

    def __init__(self,
                 uuid=None,
                 name=None,
                 portfolio_type=None,
                 created=None,
                 balance=None,
                 performance=None,
                 deposit_reference=None,
                 risk_level=None,
                 time_horizon=None,
                 status=None,
                 extra_data=None,
                 currency=None,
                 activated=None,
                 advisor=None,
                 advice_engine=None):
        """Constructor for the PortfolioDetail class"""

        # Initialize members of the class
        self.uuid = uuid
        self.name = name
        self.portfolio_type = portfolio_type
        self.risk_level = risk_level
        self.time_horizon = time_horizon
        self.status = status
        self.extra_data = extra_data
        self.currency = currency
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.activated = APIHelper.RFC3339DateTime(activated) if activated else None
        self.balance = balance
        self.performance = performance
        self.deposit_reference = deposit_reference
        self.advisor = advisor
        self.advice_engine = advice_engine

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        name = dictionary.get('name')
        portfolio_type = dictionary.get('portfolio_type')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        balance = dictionary.get('balance')
        performance = dictionary.get('performance')
        deposit_reference = dictionary.get('deposit_reference')
        risk_level = dictionary.get('risk_level')
        time_horizon = dictionary.get('time_horizon')
        status = dictionary.get('status')
        extra_data = dictionary.get('extra_data')
        currency = dictionary.get('currency')
        activated = APIHelper.RFC3339DateTime.from_value(dictionary.get("activated")).datetime if dictionary.get("activated") else None
        advisor = dictionary.get('advisor')
        advice_engine = dictionary.get('advice_engine')

        # Return an object of this model
        return cls(uuid,
                   name,
                   portfolio_type,
                   created,
                   balance,
                   performance,
                   deposit_reference,
                   risk_level,
                   time_horizon,
                   status,
                   extra_data,
                   currency,
                   activated,
                   advisor,
                   advice_engine)
