# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
import dateutil.parser


class PortfolioPerformance(object):

    """Implementation of the 'PortfolioPerformance' model.

    TODO: type model description here.

    Attributes:
        valuation_date (date): TODO: type description here.
        percentage (float): TODO: type description here.
        performance (float): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "valuation_date": 'valuation_date',
        "percentage": 'percentage',
        "performance": 'performance'
    }

    def __init__(self,
                 valuation_date=None,
                 percentage=0,
                 performance=0):
        """Constructor for the PortfolioPerformance class"""

        # Initialize members of the class
        self.valuation_date = valuation_date
        self.percentage = percentage
        self.performance = performance

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        valuation_date = dateutil.parser.parse(dictionary.get('valuation_date')).date() if dictionary.get('valuation_date') else None
        percentage = dictionary.get("percentage") if dictionary.get("percentage") else 0
        performance = dictionary.get("performance") if dictionary.get("performance") else 0

        # Return an object of this model
        return cls(valuation_date,
                   percentage,
                   performance)
