# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class PortfolioTypeRestrictions(object):

    """Implementation of the 'PortfolioTypeRestrictions' model.

    TODO: type model description here.

    Attributes:
        portfolio_type (string): TODO: type description here.
        key (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "portfolio_type": 'portfolio_type',
        "key": 'key'
    }

    def __init__(self,
                 portfolio_type=None,
                 key=None):
        """Constructor for the PortfolioTypeRestrictions class"""

        # Initialize members of the class
        self.portfolio_type = portfolio_type
        self.key = key

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        portfolio_type = dictionary.get('portfolio_type')
        key = dictionary.get('key')

        # Return an object of this model
        return cls(portfolio_type,
                   key)
