# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class Price(object):

    """Implementation of the 'Price' model.

    TODO: type model description here.

    Attributes:
        amount (float): TODO: type description here.
        datetime (datetime): TODO: type description here.
        date (datetime): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "amount": 'amount',
        "datetime": 'datetime',
        "date": 'date'
    }

    def __init__(self,
                 amount=None,
                 datetime=None,
                 date=None):
        """Constructor for the Price class"""

        # Initialize members of the class
        self.amount = amount
        self.datetime = APIHelper.RFC3339DateTime(datetime) if datetime else None
        self.date = APIHelper.RFC3339DateTime(date) if date else None

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        amount = dictionary.get('amount')
        datetime = APIHelper.RFC3339DateTime.from_value(dictionary.get("datetime")).datetime if dictionary.get("datetime") else None
        date = APIHelper.RFC3339DateTime.from_value(dictionary.get("date")).datetime if dictionary.get("date") else None

        # Return an object of this model
        return cls(amount,
                   datetime,
                   date)
