# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RebalanceStatusEnum(object):

    """Implementation of the 'RebalanceStatusEnum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        CREATED: TODO: type description here.
        ADVICE_REQUESTED: TODO: type description here.
        ADVICE_COMPLETED: TODO: type description here.
        IN_PROCESS: TODO: type description here.
        PROCESSING: TODO: type description here.
        ORDERS_GENERATED: TODO: type description here.
        ORDERS_FILLED: TODO: type description here.
        SELL_TRADES_GENERATED: TODO: type description here.
        BUY_TRADES_GENERATED: TODO: type description here.
        POSITIONS_SOLD: TODO: type description here.
        COMPLETED: TODO: type description here.
        CANCELLED: TODO: type description here.
        ERROR: TODO: type description here.

    """

    PENDING = 'PENDING'

    CREATED = 'CREATED'

    ADVICE_REQUESTED = 'ADVICE_REQUESTED'

    ADVICE_COMPLETED = 'ADVICE_COMPLETED'

    IN_PROCESS = 'IN_PROCESS'

    PROCESSING = 'PROCESSING'

    ORDERS_GENERATED = 'ORDERS_GENERATED'

    ORDERS_FILLED = 'ORDERS_FILLED'

    SELL_TRADES_GENERATED = 'SELL_TRADES_GENERATED'

    BUY_TRADES_GENERATED = 'BUY_TRADES_GENERATED'

    POSITIONS_SOLD = 'POSITIONS_SOLD'

    COMPLETED = 'COMPLETED'

    CANCELLED = 'CANCELLED'

    ERROR = 'ERROR'
