# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Response(object):

    """Implementation of the 'Response' model.

    TODO: type model description here.

    Attributes:
        status (string): TODO: type description here.
        error (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "status": 'status',
        "error": 'error'
    }

    def __init__(self,
                 status='ok',
                 error=None):
        """Constructor for the Response class"""

        # Initialize members of the class
        self.status = status
        self.error = error

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        status = dictionary.get("status") if dictionary.get("status") else 'ok'
        error = dictionary.get('error')

        # Return an object of this model
        return cls(status,
                   error)
