# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class RiskChoiceQuestionCode(object):

    """Implementation of the 'RiskChoiceQuestionCode' model.

    TODO: type model description here.

    Attributes:
        code (string): TODO: type description here.
        order (int): TODO: type description here.
        description (string): TODO: type description here.
        created (datetime): TODO: type description here.
        question_code (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "code": 'code',
        "created": 'created',
        "question_code": 'question_code',
        "order": 'order',
        "description": 'description'
    }

    def __init__(self,
                 code=None,
                 created=None,
                 question_code=None,
                 order=None,
                 description=None):
        """Constructor for the RiskChoiceQuestionCode class"""

        # Initialize members of the class
        self.code = code
        self.order = order
        self.description = description
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.question_code = question_code

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        code = dictionary.get('code')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        question_code = dictionary.get('question_code')
        order = dictionary.get('order')
        description = dictionary.get('description')

        # Return an object of this model
        return cls(code,
                   created,
                   question_code,
                   order,
                   description)
