# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status14bEnum(object):

    """Implementation of the 'Status14bEnum' enum.

    TODO: type enum description here.

    Attributes:
        DRAFT: TODO: type description here.
        PENDING: TODO: type description here.
        PROCESSING: TODO: type description here.
        POSITIONS_SOLD: TODO: type description here.
        REQUESTED: TODO: type description here.
        COMPLETED: TODO: type description here.
        ERROR: TODO: type description here.
        CANCELLED: TODO: type description here.

    """

    DRAFT = 'DRAFT'

    PENDING = 'PENDING'

    PROCESSING = 'PROCESSING'

    POSITIONS_SOLD = 'POSITIONS_SOLD'

    REQUESTED = 'REQUESTED'

    COMPLETED = 'COMPLETED'

    ERROR = 'ERROR'

    CANCELLED = 'CANCELLED'
