# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status181Enum(object):

    """Implementation of the 'Status181Enum' enum.

    TODO: type enum description here.

    Attributes:
        GENERATING: TODO: type description here.
        ERROR: TODO: type description here.
        COMPLETED: TODO: type description here.

    """

    GENERATING = 'GENERATING'

    ERROR = 'ERROR'

    COMPLETED = 'COMPLETED'
