# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status260Enum(object):

    """Implementation of the 'Status260Enum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        CHARGED: TODO: type description here.

    """

    PENDING = 'PENDING'

    CHARGED = 'CHARGED'
