# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusB65Enum(object):

    """Implementation of the 'StatusB65Enum' enum.

    TODO: type enum description here.

    Attributes:
        ONBOARDING: TODO: type description here.
        PENDING: TODO: type description here.
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.
        CUSTODIAN_PENDING: TODO: type description here.
        KYC_PENDING: TODO: type description here.

    """

    ONBOARDING = 'ONBOARDING'

    PENDING = 'PENDING'

    ACTIVE = 'ACTIVE'

    INACTIVE = 'INACTIVE'

    CUSTODIAN_PENDING = 'CUSTODIAN_PENDING'

    KYC_PENDING = 'KYC_PENDING'
