# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusB6aEnum(object):

    """Implementation of the 'StatusB6aEnum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        REQUESTED: TODO: type description here.
        PROCESSING: TODO: type description here.
        COMPLETED: TODO: type description here.
        ERROR: TODO: type description here.
        CANCELLED: TODO: type description here.

    """

    PENDING = 'PENDING'

    REQUESTED = 'REQUESTED'

    PROCESSING = 'PROCESSING'

    COMPLETED = 'COMPLETED'

    ERROR = 'ERROR'

    CANCELLED = 'CANCELLED'
