# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class StatusBd7Enum(object):

    """Implementation of the 'StatusBd7Enum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        PROCESSING: TODO: type description here.
        COMPLETED: TODO: type description here.
        PAUSED: TODO: type description here.
        REOPENED: TODO: type description here.
        OTHER: TODO: type description here.
        ERROR: TODO: type description here.
        CANCELLED: TODO: type description here.
        OUTDATED: TODO: type description here.

    """

    PENDING = 'PENDING'

    PROCESSING = 'PROCESSING'

    COMPLETED = 'COMPLETED'

    PAUSED = 'PAUSED'

    REOPENED = 'REOPENED'

    OTHER = 'OTHER'

    ERROR = 'ERROR'

    CANCELLED = 'CANCELLED'

    OUTDATED = 'OUTDATED'
