# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status6f6Enum(object):

    """Implementation of the 'Status6f6Enum' enum.

    TODO: type enum description here.

    Attributes:
        ACTIVE: TODO: type description here.
        INACTIVE: TODO: type description here.
        DELETED: TODO: type description here.

    """

    ACTIVE = 'ACTIVE'

    INACTIVE = 'INACTIVE'

    DELETED = 'DELETED'
