# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Status2efEnum(object):

    """Implementation of the 'Status2efEnum' enum.

    TODO: type enum description here.

    Attributes:
        PENDING: TODO: type description here.
        ACTIVE: TODO: type description here.
        DELETING: TODO: type description here.
        DELETED: TODO: type description here.

    """

    PENDING = 'PENDING'

    ACTIVE = 'ACTIVE'

    DELETING = 'DELETING'

    DELETED = 'DELETED'
