# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TargetEnum(object):

    """Implementation of the 'target' enum.

    TODO: type enum description here.

    Attributes:
        ENUM_1: TODO: type description here.
        ENUM_2: TODO: type description here.
        ENUM_3: TODO: type description here.
        ENUM_4: TODO: type description here.
        ENUM_5: TODO: type description here.
        ENUM_6: TODO: type description here.
        ENUM_7: TODO: type description here.

    """

    ENUM_1 = 'cashcorporateaction'

    ENUM_2 = 'charge'

    ENUM_3 = 'deposit'

    ENUM_4 = 'portfolio'

    ENUM_5 = 'rebalance'

    ENUM_6 = 'sharescorporateaction'

    ENUM_7 = 'withdrawal'
