# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class TitleEnum(object):

    """Implementation of the 'TitleEnum' enum.

    TODO: type enum description here.

    Attributes:
        MR: TODO: type description here.
        MS: TODO: type description here.
        MX: TODO: type description here.

    """

    MR = 'MR'

    MS = 'MS'

    MX = 'MX'
