# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class Unsubscribe(object):

    """Implementation of the 'Unsubscribe' model.

    TODO: type model description here.

    Attributes:
        id (string): TODO: type description here.
        subscription (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "id": 'id',
        "subscription": 'subscription'
    }

    def __init__(self,
                 id=None,
                 subscription=None):
        """Constructor for the Unsubscribe class"""

        # Initialize members of the class
        self.id = id
        self.subscription = subscription

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        id = dictionary.get('id')
        subscription = dictionary.get('subscription')

        # Return an object of this model
        return cls(id,
                   subscription)
