# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ValueUnitEnum(object):

    """Implementation of the 'ValueUnitEnum' enum.

    TODO: type enum description here.

    Attributes:
        FIXED_AMOUNT: TODO: type description here.
        PERCENTAGE: TODO: type description here.

    """

    FIXED_AMOUNT = 'fixed_amount'

    PERCENTAGE = 'percentage'
