# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class VerifyTypeEnum(object):

    """Implementation of the 'VerifyTypeEnum' enum.

    TODO: type enum description here.

    Attributes:
        IDENTITY: TODO: type description here.
        BANKING: TODO: type description here.

    """

    IDENTITY = 'IDENTITY'

    BANKING = 'BANKING'
