# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class VerificationList(object):

    """Implementation of the 'VerificationList' model.

    A ModelSerializer that takes additional arguments for
    "fields", "omit" and "expand" in order to
    control which fields are displayed, and whether to replace simple
    values with complex, nested serializations

    Attributes:
        uuid (uuid|string): TODO: type description here.
        verify_type (VerifyTypeEnum): TODO: type description here.
        status (StatusBd7Enum): TODO: type description here.
        result (ResultEnum): TODO: type description here.
        created (datetime): TODO: type description here.
        updated (datetime): TODO: type description here.
        verification_documents (list of string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "verify_type": 'verify_type',
        "status": 'status',
        "result": 'result',
        "created": 'created',
        "updated": 'updated',
        "verification_documents": 'verification_documents'
    }

    def __init__(self,
                 uuid=None,
                 verify_type=None,
                 status=None,
                 result=None,
                 created=None,
                 updated=None,
                 verification_documents=None):
        """Constructor for the VerificationList class"""

        # Initialize members of the class
        self.uuid = uuid
        self.verify_type = verify_type
        self.status = status
        self.result = result
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.updated = APIHelper.RFC3339DateTime(updated) if updated else None
        self.verification_documents = verification_documents

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        verify_type = dictionary.get('verify_type')
        status = dictionary.get('status')
        result = dictionary.get('result')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        updated = APIHelper.RFC3339DateTime.from_value(dictionary.get("updated")).datetime if dictionary.get("updated") else None
        verification_documents = dictionary.get('verification_documents')

        # Return an object of this model
        return cls(uuid,
                   verify_type,
                   status,
                   result,
                   created,
                   updated,
                   verification_documents)
