# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.models.document import Document


class VerificationDocumentCreate(object):

    """Implementation of the 'VerificationDocumentCreate' model.

    TODO: type model description here.

    Attributes:
        document_type (string): TODO: type description here.
        uuid (uuid|string): TODO: type description here.
        document_front (Document): TODO: type description here.
        document_back (Document): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "document_type": 'document_type',
        "uuid": 'uuid',
        "document_front": 'document_front',
        "document_back": 'document_back'
    }

    def __init__(self,
                 document_type=None,
                 uuid=None,
                 document_front=None,
                 document_back=None):
        """Constructor for the VerificationDocumentCreate class"""

        # Initialize members of the class
        self.document_type = document_type
        self.uuid = uuid
        self.document_front = document_front
        self.document_back = document_back

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        document_type = dictionary.get('document_type')
        uuid = dictionary.get('uuid')
        document_front = Document.from_dictionary(dictionary.get('document_front')) if dictionary.get('document_front') else None
        document_back = Document.from_dictionary(dictionary.get('document_back')) if dictionary.get('document_back') else None

        # Return an object of this model
        return cls(document_type,
                   uuid,
                   document_front,
                   document_back)
