# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from nucoroapiv2.api_helper import APIHelper


class WithdrawalDetail(object):

    """Implementation of the 'WithdrawalDetail' model.

    TODO: type model description here.

    Attributes:
        uuid (uuid|string): TODO: type description here.
        portfolio (string): TODO: type description here.
        amount (float): TODO: type description here.
        provider (string): TODO: type description here.
        status (Status14bEnum): TODO: type description here.
        reason (string): Cancelled reason
        completed (datetime): TODO: type description here.
        purpose (string): Withdrawal reason
        created (datetime): TODO: type description here.
        withdrawal_type (string): TODO: type description here.
        extra_data (dict): Additional withdrawal attributes for the specific
            portal

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "uuid": 'uuid',
        "portfolio": 'portfolio',
        "amount": 'amount',
        "provider": 'provider',
        "status": 'status',
        "created": 'created',
        "withdrawal_type": 'withdrawal_type',
        "reason": 'reason',
        "completed": 'completed',
        "purpose": 'purpose',
        "extra_data": 'extra_data'
    }

    def __init__(self,
                 uuid=None,
                 portfolio=None,
                 amount=None,
                 provider=None,
                 status=None,
                 created=None,
                 withdrawal_type=None,
                 reason=None,
                 completed=None,
                 purpose=None,
                 extra_data=None):
        """Constructor for the WithdrawalDetail class"""

        # Initialize members of the class
        self.uuid = uuid
        self.portfolio = portfolio
        self.amount = amount
        self.provider = provider
        self.status = status
        self.reason = reason
        self.completed = APIHelper.RFC3339DateTime(completed) if completed else None
        self.purpose = purpose
        self.created = APIHelper.RFC3339DateTime(created) if created else None
        self.withdrawal_type = withdrawal_type
        self.extra_data = extra_data

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary
        uuid = dictionary.get('uuid')
        portfolio = dictionary.get('portfolio')
        amount = dictionary.get('amount')
        provider = dictionary.get('provider')
        status = dictionary.get('status')
        created = APIHelper.RFC3339DateTime.from_value(dictionary.get("created")).datetime if dictionary.get("created") else None
        withdrawal_type = dictionary.get('withdrawal_type')
        reason = dictionary.get('reason')
        completed = APIHelper.RFC3339DateTime.from_value(dictionary.get("completed")).datetime if dictionary.get("completed") else None
        purpose = dictionary.get('purpose')
        extra_data = dictionary.get('extra_data')

        # Return an object of this model
        return cls(uuid,
                   portfolio,
                   amount,
                   provider,
                   status,
                   created,
                   withdrawal_type,
                   reason,
                   completed,
                   purpose,
                   extra_data)
