# -*- coding: utf-8 -*-

"""
nucoroapiv2

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from nucoroapiv2.decorators import lazy_property
from nucoroapiv2.configuration import Configuration
from nucoroapiv2.configuration import Environment
from nucoroapiv2.controllers.api_controller import ApiController
from nucoroapiv2.controllers.auth_controller import AuthController
from nucoroapiv2.controllers.application_controller\
    import ApplicationController


class Nucoroapiv2Client(object):

    @lazy_property
    def api(self):
        return ApiController(self.config)

    @lazy_property
    def auth(self):
        return AuthController(self.config)

    @lazy_property
    def application(self):
        return ApplicationController(self.config)

    def __init__(self, timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION,
                 default_host='www.example.com', config=None):
        if config is None:
            self.config = Configuration(timeout=timeout,
                                        max_retries=max_retries,
                                        backoff_factor=backoff_factor,
                                        retry_statuses=retry_statuses,
                                        retry_methods=retry_methods,
                                        environment=environment,
                                        default_host=default_host)
        else:
            self.config = config
